grade1=input("First grade:")
grade1=eval(grade1)
grade2=input("Second grade:")
grade2=eval(grade2)
grade3=input("Third grade:")
grade3=eval(grade3)
weight1=input("First weight:")
weight1=eval(weight1)
weight2=input("Second weight:")
weight2=eval(weight2)
weight3=input("Third weight:")
weight3=eval(weight3)

gradepoint=(grade1*weight1+grade2*weight2+grade3*weight3) / (weight1+weight2+weight3)
print(f'The grade-point average is: {gradepoint}')